name: Publish Firestore Emulator

on:
  push:
    branches:
      - main
    paths:
      - firestore/Dockerfile
      - .github/workflows/publish-firestore.yml
      - .github/workflows/reusable-publish-emulator.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/reusable-publish-emulator.yml
    with:
      image-name: firestore-emulator
      build-context: firestore
      version-command: |-
        echo "version=$(head -n 1 firestore/Dockerfile | cut -d ':' -f 2 | cut -d '-' -f 1)" >> $GITHUB_OUTPUT
      smoke-test-port: "8080"
      cache-scope: publish-firestore
      database-mode: datastore-mode
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
