name: Publish Pub/Sub Emulator

on:
  push:
    branches:
      - main
    paths:
      - pubsub/Dockerfile
      - .github/workflows/publish-pubsub.yml
      - .github/workflows/reusable-publish-emulator.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/reusable-publish-emulator.yml
    with:
      image-name: pubsub-emulator
      build-context: pubsub
      version-command: |-
        echo "version=$(head -n 1 pubsub/Dockerfile | cut -d ':' -f 2 | cut -d '-' -f 1)" >> $GITHUB_OUTPUT
      smoke-test-port: "8085"
      cache-scope: publish-pubsub
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
